---
title: "Database Tables"
description: |
  In this blog I will exlpain some best practices for new or excisting businesses that are beginning to create a database and setting up tables within that database.
author:
  - name: Zach Young 
    url: 
    affiliation: Brigham Young University-Idaho
date: 05-22-2021
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Learn more about creating blogs with Distill at:
# https://rstudio.github.io/distill/blog.html

```

A database is made up of many different tables that store all of your organizations data. These tables are usually connected in some way. In order for your database to be most effective and help your company with data analysis, you should make it easy to navigate through. To help with easy navigation you should make sure that your tables are set up correctly. 

When creating a table you should first study your data and determine what data type it is. If you store your data as the wrong data type you wont be able to use the data in the way that you are expecting to. For example, if you store sales amounts as a string, you then wont be able to add those amounts up or do other calculations. 

Naming the tables will also help immensely with the ease of using a database. You want the titles of the tables and columns within the tables to be easy to understand so that when new employees begin working they wont have to decipher what the tables mean. Also you will want to name each table and column uniquely. When you are working with a table and all the columns are named almost the exact thing, it can get confusing and also hard to remember what each column is storing.

As well, when you are doing analysis with your data and you find yourself having to do many external calculations outside of your database, you can create a VIEW within your database. A VIEW in SQL Server is like a virtual table that contains data from one or multiple tables. It does not hold any data and does not exist physically in the database. It simply contains a set of predefined SQL queries to fetch data from the database. This allows you to have calculations that you constantly make outside of the database already available to you for data analysis.